In [1]:
from datascience import *
import numpy as np
import matplotlib.pyplot as plt 
%matplotlib inline
plt.style.use('fivethirtyeight')

## 1/ Nearest neighbors

In [2]:
ckd = Table.read_table('../../Data/ChronicKidneyDisease.csv')
ckd

id   | age  | bp   | sg    | al   | su   | rbc      | pc       | pcc        | ba         | bgr  | bu   | sc   | sod  | pot  | hemo | pcv  | wc    | rc   | htn  | dm   | cad  | appet | pe   | ane  | classification
0    | 48   | 80   | 1.02  | 1    | 0    | nan      | normal   | notpresent | notpresent | 121  | 36   | 1.2  | nan  | nan  | 15.4 | 44   | 7800  | 5.2  | yes  | yes  | no   | good  | no   | no   | ckd
1    | 7    | 50   | 1.02  | 4    | 0    | nan      | normal   | notpresent | notpresent | nan  | 18   | 0.8  | nan  | nan  | 11.3 | 38   | 6000  | nan  | no   | no   | no   | good  | no   | no   | ckd
2    | 62   | 80   | 1.01  | 2    | 3    | normal   | normal   | notpresent | notpresent | 423  | 53   | 1.8  | nan  | nan  | 9.6  | 31   | 7500  | nan  | no   | yes  | no   | poor  | no   | yes  | ckd
3    | 48   | 70   | 1.005 | 4    | 0    | normal   | abnormal | present    | notpresent | 117  | 56   | 3.8  | 111  | 2.5  | 11.2 | 32   | 6700  | 3.9  | yes  | no   | no   | poor  | yes  | yes  | ckd
4    | 51   | 80   | 1.01  | 2    | 0    | normal   | normal   | notpresent | notpresent | 106  | 26   | 1.4  | nan  | nan  | 11.6 | 35   | 7300  | 4.6  | no   | no   | no   | good  | no   | no   | ckd
5    | 60   | 90   | 1.015 | 3    | 0    | nan      | nan      | notpresent | notpresent | 74   | 25   | 1.1  | 142  | 3.2  | 12.2 | 39   | 7800  | 4.4  | yes  | yes  | no   | good  | yes  | no   | ckd
6    | 68   | 70   | 1.01  | 0    | 0    | nan      | normal   | notpresent | notpresent | 100  | 54   | 24   | 104  | 4    | 12.4 | 36   | nan   | nan  | no   | no   | no   | good  | no   | no   | ckd
7    | 24   | nan  | 1.015 | 2    | 4    | normal   | abnormal | notpresent | notpresent | 410  | 31   | 1.1  | nan  | nan  | 12.4 | 44   | 6900  | 5    | no   | yes  | no   | good  | yes  | no   | ckd
8    | 52   | 100  | 1.015 | 3    | 0    | normal   | abnormal | present    | notpresent | 138  | 60   | 1.9  | nan  | nan  | 10.8 | 33   | 9600  | 4.0  | yes  | yes  | no   | good  | no   | yes  | ckd
9    | 53   | 90   | 1.02  | 2    | 0    | abnormal | abnormal | present    | notpresent | 70   | 107  | 7.2  | 114  | 3.7  | 9.5  | 29   | 12100 | 3.7  | yes  | yes  | no   | poor  | no   | yes  | ckd
... (390 rows omitted)

In [8]:
def classifi(string):
    if string == 'ckd':
        return 1
    else:
        return 0
ckd = ckd.with_column( 
    'class' ,ckd.apply(classifi,'classification')
)
ckd

id   | age  | bp   | sg    | al   | su   | rbc      | pc       | pcc        | ba         | bgr  | bu   | sc   | sod  | pot  | hemo | pcv  | wc    | rc   | htn  | dm   | cad  | appet | pe   | ane  | classification | class
0    | 48   | 80   | 1.02  | 1    | 0    | nan      | normal   | notpresent | notpresent | 121  | 36   | 1.2  | nan  | nan  | 15.4 | 44   | 7800  | 5.2  | yes  | yes  | no   | good  | no   | no   | ckd            | 1
1    | 7    | 50   | 1.02  | 4    | 0    | nan      | normal   | notpresent | notpresent | nan  | 18   | 0.8  | nan  | nan  | 11.3 | 38   | 6000  | nan  | no   | no   | no   | good  | no   | no   | ckd            | 1
2    | 62   | 80   | 1.01  | 2    | 3    | normal   | normal   | notpresent | notpresent | 423  | 53   | 1.8  | nan  | nan  | 9.6  | 31   | 7500  | nan  | no   | yes  | no   | poor  | no   | yes  | ckd            | 1
3    | 48   | 70   | 1.005 | 4    | 0    | normal   | abnormal | present    | notpresent | 117  | 56   | 3.8  | 111  | 2.5  | 11.2 | 32   | 6700  | 3.9  | yes  | no   | no   | poor  | yes  | yes  | ckd            | 1
4    | 51   | 80   | 1.01  | 2    | 0    | normal   | normal   | notpresent | notpresent | 106  | 26   | 1.4  | nan  | nan  | 11.6 | 35   | 7300  | 4.6  | no   | no   | no   | good  | no   | no   | ckd            | 1
5    | 60   | 90   | 1.015 | 3    | 0    | nan      | nan      | notpresent | notpresent | 74   | 25   | 1.1  | 142  | 3.2  | 12.2 | 39   | 7800  | 4.4  | yes  | yes  | no   | good  | yes  | no   | ckd            | 1
6    | 68   | 70   | 1.01  | 0    | 0    | nan      | normal   | notpresent | notpresent | 100  | 54   | 24   | 104  | 4    | 12.4 | 36   | nan   | nan  | no   | no   | no   | good  | no   | no   | ckd            | 1
7    | 24   | nan  | 1.015 | 2    | 4    | normal   | abnormal | notpresent | notpresent | 410  | 31   | 1.1  | nan  | nan  | 12.4 | 44   | 6900  | 5    | no   | yes  | no   | good  | yes  | no   | ckd            | 1
8    | 52   | 100  | 1.015 | 3    | 0    | normal   | abnormal | present    | notpresent | 138  | 60   | 1.9  | nan  | nan  | 10.8 | 33   | 9600  | 4.0  | yes  | yes  | no   | good  | no   | yes  | ckd            | 1
9    | 53   | 90   | 1.02  | 2    | 0    | abnormal | abnormal | present    | notpresent | 70   | 107  | 7.2  | 114  | 3.7  | 9.5  | 29   | 12100 | 3.7  | yes  | yes  | no   | poor  | no   | yes  | ckd            | 1
... (390 rows omitted)

In [16]:
def standard_unit(array):
    return (array - np.mean(array))/np.std(array)

In [ ]:
mask1 = ~np.isnan(ckd.column('hemo'))
def clean_wc(x):
    x = str(x).strip()  # bỏ tab và khoảng trắng
    if x == '?':
        return np.nan
    return float(x)

wc = np.array([clean_wc(x) for x in ckd.column('wc')])
mask = ~np.isnan(wc)
ckd1 = ckd.where(mask).where(mask1)


# ckd1 = Table().with_columns(
#     'Hemoglobin', standard_unit(ckd.column('hemo')),
#     'Glucose', standard_unit(ckd.column('bgr')),
#     'White Blood Cell Count', standard_unit(ckd.column('wc').astype(float)),
#     'Class', ckd.column('class')        
# )
# ckd1

id   | age  | bp   | sg    | al   | su   | rbc      | pc       | pcc        | ba         | bgr  | bu   | sc   | sod  | pot  | hemo | pcv  | wc    | rc   | htn  | dm   | cad  | appet | pe   | ane  | classification | class
0    | 48   | 80   | 1.02  | 1    | 0    | nan      | normal   | notpresent | notpresent | 121  | 36   | 1.2  | nan  | nan  | 15.4 | 44   | 7800  | 5.2  | yes  | yes  | no   | good  | no   | no   | ckd            | 1
1    | 7    | 50   | 1.02  | 4    | 0    | nan      | normal   | notpresent | notpresent | nan  | 18   | 0.8  | nan  | nan  | 11.3 | 38   | 6000  | nan  | no   | no   | no   | good  | no   | no   | ckd            | 1
2    | 62   | 80   | 1.01  | 2    | 3    | normal   | normal   | notpresent | notpresent | 423  | 53   | 1.8  | nan  | nan  | 9.6  | 31   | 7500  | nan  | no   | yes  | no   | poor  | no   | yes  | ckd            | 1
3    | 48   | 70   | 1.005 | 4    | 0    | normal   | abnormal | present    | notpresent | 117  | 56   | 3.8  | 111  | 2.5  | 11.2 | 32   | 6700  | 3.9  | yes  | no   | no   | poor  | yes  | yes  | ckd            | 1
4    | 51   | 80   | 1.01  | 2    | 0    | normal   | normal   | notpresent | notpresent | 106  | 26   | 1.4  | nan  | nan  | 11.6 | 35   | 7300  | 4.6  | no   | no   | no   | good  | no   | no   | ckd            | 1
5    | 60   | 90   | 1.015 | 3    | 0    | nan      | nan      | notpresent | notpresent | 74   | 25   | 1.1  | 142  | 3.2  | 12.2 | 39   | 7800  | 4.4  | yes  | yes  | no   | good  | yes  | no   | ckd            | 1
7    | 24   | nan  | 1.015 | 2    | 4    | normal   | abnormal | notpresent | notpresent | 410  | 31   | 1.1  | nan  | nan  | 12.4 | 44   | 6900  | 5    | no   | yes  | no   | good  | yes  | no   | ckd            | 1
8    | 52   | 100  | 1.015 | 3    | 0    | normal   | abnormal | present    | notpresent | 138  | 60   | 1.9  | nan  | nan  | 10.8 | 33   | 9600  | 4.0  | yes  | yes  | no   | good  | no   | yes  | ckd            | 1
9    | 53   | 90   | 1.02  | 2    | 0    | abnormal | abnormal | present    | notpresent | 70   | 107  | 7.2  | 114  | 3.7  | 9.5  | 29   | 12100 | 3.7  | yes  | yes  | no   | poor  | no   | yes  | ckd            | 1
11   | 63   | 70   | 1.01  | 3    | 0    | abnormal | abnormal | present    | notpresent | 380  | 60   | 2.7  | 131  | 4.2  | 10.8 | 32   | 4500  | 3.8  | yes  | yes  | no   | poor  | yes  | no   | ckd            | 1
... (284 rows omitted)