In [1]:
import matplotlib.pyplot as plots
%matplotlib inline
plots.style.use('fivethirtyeight')

## 1 Phan vi P

In [2]:
import numpy as np
from datascience import *
s = [1,4,6,2,5]
s = np.sort(s)
percentile(85,s)

6

## 2 bootstrap

2.1 Test bootstap 1

In [3]:
population = Table.read_table('../../Data/san_francisco_2019.csv')
population

Organization Group | Department      | Job Family                    | Job                            | Salary | Overtime | Benefits | Total Compensation
Public Protection  | Adult Probation | Information Systems           | IS Trainer-Journey             | 91332  | 0        | 40059    | 131391
Public Protection  | Adult Probation | Information Systems           | IS Engineer-Assistant          | 123241 | 0        | 49279    | 172520
Public Protection  | Adult Probation | Information Systems           | IS Business Analyst-Senior     | 115715 | 0        | 46752    | 162468
Public Protection  | Adult Probation | Information Systems           | IS Business Analyst-Principal  | 159394 | 0        | 57312    | 216706
Public Protection  | Adult Probation | Information Systems           | IS Programmer Analyst          | 70035  | 0        | 28671    | 98706
Public Protection  | Adult Probation | Information Systems           | IS Project Director            | 175742 | 0        | 60830    | 236572
Public Protection  | Adult Probation | Information Systems           | IT Operations Support Admin IV | 123840 | 0        | 49429    | 173269
Public Protection  | Adult Probation | Payroll, Billing & Accounting | Accountant III                 | 111816 | 0        | 46319    | 158135
Public Protection  | Adult Probation | Budget, Admn & Stats Analysis | Statistician                   | 87725  | 0        | 38899    | 126624
Public Protection  | Adult Probation | Budget, Admn & Stats Analysis | Senior Administrative Analyst  | 116192 | 0        | 47651    | 163843
... (44515 rows omitted)

In [4]:
population.sample(5,with_replacement= False) ## Lay mot bang gom 5 dong bat ky tu bang ban dau, khong hoan lai

Organization Group                      | Department                     | Job Family                    | Job                          | Salary | Overtime | Benefits | Total Compensation
Public Works, Transportation & Commerce | Airport Commission             | Professional Engineering      | Assoc Engineer               | 121138 | 0        | 47081    | 168219
Community Health                        | Public Health                  | Med Therapy & Auxiliary       | Health Program Coordinator 3 | 126968 | 0        | 49965    | 176933
Community Health                        | Public Health                  | Nursing                       | Patient Care Assistant       | 71140  | 39422    | 34362    | 144924
Culture & Recreation                    | Recreation And Park Commission | Agriculture & Horticulture    | Gardener                     | 47603  | 544      | 19548    | 67695
Culture & Recreation                    | Art Commission                 | Budget, Admn & Stats Analysis | Management Assistant         | 88648  | 0        | 38985    | 127634

In [5]:
population.sort('Total Compensation',descending= True)

Organization Group               | Department          | Job Family                    | Job                          | Salary | Overtime | Benefits | Total Compensation
General Administration & Finance | Retirement Services | Administrative & Mgmt (Unrep) | Chief Investment Officer     | 577633 | 0        | 146398   | 724031
General Administration & Finance | Retirement Services | Unassigned                    | Managing Director            | 483072 | 0        | 134879   | 617951
General Administration & Finance | Retirement Services | Unassigned                    | Managing Director            | 482649 | 0        | 134905   | 617554
General Administration & Finance | Retirement Services | Unassigned                    | Managing Director            | 451507 | 0        | 120276   | 571784
General Administration & Finance | Retirement Services | Unassigned                    | Managing Director            | 449378 | 0        | 120857   | 570235
Community Health                 | Public Health       | Administrative & Mgmt (Unrep) | Physician Administrator, DPH | 434966 | 0        | 119213   | 554179
Public Protection                | Sheriff             | Correction & Detention        | Senior Deputy Sheriff        | 152153 | 315896   | 77275    | 545324
General Administration & Finance | Retirement Services | Management                    | Director                     | 397392 | 0        | 108913   | 506305
Community Health                 | Public Health       | Medical & Dental              | Supervising Physician Spec   | 404701 | 0        | 99480    | 504181
Community Health                 | Public Health       | Medical & Dental              | Senior Physician Specialist  | 400992 | 0        | 97428    | 498421
... (44515 rows omitted)

In [6]:
population.hist('Total Compensation', bins = np.arange(0,800000,25000))

In [7]:
minsalary = 15*20*50
population = population.where('Salary', are.above(minsalary))
population

Organization Group | Department      | Job Family                    | Job                            | Salary | Overtime | Benefits | Total Compensation
Public Protection  | Adult Probation | Information Systems           | IS Trainer-Journey             | 91332  | 0        | 40059    | 131391
Public Protection  | Adult Probation | Information Systems           | IS Engineer-Assistant          | 123241 | 0        | 49279    | 172520
Public Protection  | Adult Probation | Information Systems           | IS Business Analyst-Senior     | 115715 | 0        | 46752    | 162468
Public Protection  | Adult Probation | Information Systems           | IS Business Analyst-Principal  | 159394 | 0        | 57312    | 216706
Public Protection  | Adult Probation | Information Systems           | IS Programmer Analyst          | 70035  | 0        | 28671    | 98706
Public Protection  | Adult Probation | Information Systems           | IS Project Director            | 175742 | 0        | 60830    | 236572
Public Protection  | Adult Probation | Information Systems           | IT Operations Support Admin IV | 123840 | 0        | 49429    | 173269
Public Protection  | Adult Probation | Payroll, Billing & Accounting | Accountant III                 | 111816 | 0        | 46319    | 158135
Public Protection  | Adult Probation | Budget, Admn & Stats Analysis | Statistician                   | 87725  | 0        | 38899    | 126624
Public Protection  | Adult Probation | Budget, Admn & Stats Analysis | Senior Administrative Analyst  | 116192 | 0        | 47651    | 163843
... (37093 rows omitted)

In [8]:
population.hist('Total Compensation', bins = np.arange(0,800000,25000))

In [9]:
unknown_median = percentile(50,population.column('Total Compensation')) # median cua population
unknown_median

135747.0

In [10]:
a_sample = population.sample(4,with_replacement= True)
a_sample

Organization Group                      | Department                     | Job Family                    | Job                   | Salary | Overtime | Benefits | Total Compensation
Community Health                        | Public Health                  | Clerical, Secretarial & Steno | Unit Clerk            | 57709  | 136      | 27174    | 85019
Culture & Recreation                    | Recreation And Park Commission | Recreation                    | Recreation Supervisor | 101723 | 0        | 43282    | 145005
Public Works, Transportation & Commerce | Municipal Transportation Agcy  | Street Transit                | Transit Operator      | 82799  | 21219    | 40365    | 144382
Community Health                        | Public Health                  | Med Therapy & Auxiliary       | Health Worker 3       | 68472  | 62       | 33748    | 102281

In [11]:
bootstrap_sample = a_sample.sample(a_sample.num_rows,with_replacement=True)
bootstrap_sample

Organization Group                      | Department                     | Job Family     | Job                   | Salary | Overtime | Benefits | Total Compensation
Culture & Recreation                    | Recreation And Park Commission | Recreation     | Recreation Supervisor | 101723 | 0        | 43282    | 145005
Public Works, Transportation & Commerce | Municipal Transportation Agcy  | Street Transit | Transit Operator      | 82799  | 21219    | 40365    | 144382
Culture & Recreation                    | Recreation And Park Commission | Recreation     | Recreation Supervisor | 101723 | 0        | 43282    | 145005
Culture & Recreation                    | Recreation And Park Commission | Recreation     | Recreation Supervisor | 101723 | 0        | 43282    | 145005