In [12]:
import numpy as np
import pandas as pd
sr_scores = pd.Series([90, 85, 78, 92, 85], index=['Alice', 'Bob', 'Charlie', 'David', 'Eva'])
df_sales = pd.DataFrame({
    "order_id": [1, 2, 3, 4, 5, 6, 7, 8],
    "product": ["Laptop", "Phone", "Tablet", "Laptop", "Phone", "Tablet", "Laptop", "Phone"],
    "price": [1000, 500, 300, 1200, 550, 320, 1100, 600],
    "quantity": [1, 2, 3, 1, 2, 1, 1, 2],
    "order_date": [
        "2024-01-01", "2024-01-02", "2024-01-03", "2024-01-04",
        "2024-01-05", "2024-01-06", "2024-01-07", "2024-01-08"
    ]
})
df_employees = pd.DataFrame({
    "employee_id": [101, 102, 103, 104, 105, 106, 107, 108],
    "name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank", "Grace", "Helen"],
    "department": ["HR", "IT", "IT", "Finance", "HR", "IT", "Finance", "HR"],
    "age": [25, 32, 29, 41, 35, 28, 45, 30],
    "salary": [50000, 70000, 65000, 90000, 62000, 72000, 88000, 58000],
    "city": ["Hanoi", "HCMC", "Hanoi", "Danang", "HCMC", "Hanoi", "Danang", "HCMC"],
    "is_active": [True, True, False, True, True, False, True, True]
})

In [13]:
dept_order = pd.Categorical(
    df_employees["department"],
    categories= ['IT','HR',"FInance"],
    ordered= True
)

df1 = df_employees.assign(
    department_order = dept_order
).sort_values(by = "department_order"
).drop(columns = "department_order")
df1

   employee_id     name department  age  salary    city  is_active
1          102      Bob         IT   32   70000    HCMC       True
2          103  Charlie         IT   29   65000   Hanoi      False
5          106    Frank         IT   28   72000   Hanoi      False
0          101    Alice         HR   25   50000   Hanoi       True
4          105      Eva         HR   35   62000    HCMC       True
7          108    Helen         HR   30   58000    HCMC       True
3          104    David    Finance   41   90000  Danang       True
6          107    Grace    Finance   45   88000  Danang       True

In [14]:
df_sales.assign(
    product_order = pd.Categorical(
        df_sales['product'],
        categories= ['Laptop','Tablets','Phone'],
        ordered= True
    )
).sort_values(
    by = 'product_order'
).drop(
    columns = 'product_order'
)

   order_id product  price  quantity  order_date
0         1  Laptop   1000         1  2024-01-01
3         4  Laptop   1200         1  2024-01-04
6         7  Laptop   1100         1  2024-01-07
1         2   Phone    500         2  2024-01-02
4         5   Phone    550         2  2024-01-05
7         8   Phone    600         2  2024-01-08
2         3  Tablet    300         3  2024-01-03
5         6  Tablet    320         1  2024-01-06

In [15]:
df_sales.assign(
    result = df_sales['price']*df_sales['quantity']
).sort_values(
    by = ['result', 'quantity'], ascending= [False,False]
).drop(
    columns = 'result'
)

   order_id product  price  quantity  order_date
7         8   Phone    600         2  2024-01-08
3         4  Laptop   1200         1  2024-01-04
4         5   Phone    550         2  2024-01-05
6         7  Laptop   1100         1  2024-01-07
1         2   Phone    500         2  2024-01-02
0         1  Laptop   1000         1  2024-01-01
2         3  Tablet    300         3  2024-01-03
5         6  Tablet    320         1  2024-01-06

In [17]:
df_employees.assign(
    department_order = pd.Categorical(
        df_employees['department'],
        categories= ['Finance', 'IT', 'HR'],
        ordered = True
    )
).sort_values(
    by = ['is_active', 'department_order','salary','age'], ascending= [False, True, False, True]
).drop(
    columns = 'department_order'
)

   employee_id     name department  age  salary    city  is_active
3          104    David    Finance   41   90000  Danang       True
6          107    Grace    Finance   45   88000  Danang       True
1          102      Bob         IT   32   70000    HCMC       True
4          105      Eva         HR   35   62000    HCMC       True
7          108    Helen         HR   30   58000    HCMC       True
0          101    Alice         HR   25   50000   Hanoi       True
5          106    Frank         IT   28   72000   Hanoi      False
2          103  Charlie         IT   29   65000   Hanoi      False